version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
      day: saturday
      time: '10:00'
  - package-ecosystem: cargo
    directory: '/'
    schedule:
      interval: weekly
      day: saturday
      time: '10:00'
    groups:
      updatable:
        applies-to: version-updates
        update-types:
          - "patch"
          - "minor"
        patterns:
          - "*"
