name: Container Image

on:
  push:
    tags: ['*']

env:
  REGISTRY: docker.io
  IMAGE_NAME: melchor9000/traefik-auth

jobs:
  build-binary:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: true
      matrix:
        target:
        - x86_64-unknown-linux-gnu
        - aarch64-unknown-linux-gnu
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross
        # run: |
        #   VERSION=$(curl -sSL https://api.github.com/repos/cross-rs/cross/releases/latest | jq -r '.tag_name')
        #   FILE_NAME="cross-x86_64-unknown-linux-gnu.tar.gz"
        #   URL="https://github.com/cross-rs/cross/releases/download/${VERSION}/${FILE_NAME}"
        #   echo Downloading "$URL"
        #   wget "$URL"
        #   echo Extracting "$FILE_NAME"
        #   tar -xvzf "${FILE_NAME}" -C $HOME/.cargo/bin

      - name: Build binary
        run: |
          cross build --target ${{ matrix.target }} --release
          mkdir dist
          tag=$(echo ${{ matrix.target }} | cut -d- -f1)
          cp target/${{ matrix.target }}/release/traefik-auth dist/traefik-auth-${tag}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary-${{ matrix.target }}
          path: dist


  # step that merges all artifacts into one
  merge:
    runs-on: ubuntu-latest
    needs: build-binary
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: binaries
          pattern: binary-*


  build-docker:
    runs-on: ubuntu-latest
    needs: merge
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          name: binaries
          path: dist/

      - name: Fix permissions
        run: chmod 755 dist/traefik-auth-*

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in into the registry
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Build and push Docker image with Buildx (don't push on PR)
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          build-args: SOURCE=binary
